## 6COM1044-0105-Machine Learning and Neural Computing
### Math Fundamentals

In [1]:
import numpy as np
from numpy.linalg import inv
from scipy.linalg import svd

In [2]:
# Define two vectors
x = [82, 90, 65, 78, 46, 50, 51] # A list
print('Vector x = ', x)

# Sum of vectors

Vector x =  [82, 90, 65, 78, 46, 50, 51]


In [3]:
# Define a matrix
M = [[82, 90, 65, 78, 46],[76, 78, 60, 50, 60]] # A list of lists = a column vector
print('Matrix M = ', M)


Matrix M =  [[82, 90, 65, 78, 46], [76, 78, 60, 50, 60]]


In [4]:
# Finding the inverse of a matrix
a = np.array([[1., 2.], [3., 4.]])
print('Matrix a:')
print(a)
print()

a_inv = inv(a)
print('Inverse of matrix a:')
print(a_inv)

Matrix a:
[[1. 2.]
 [3. 4.]]

Inverse of matrix a:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [5]:
# Finding the transpose of a matrix

a = np.array([[2., 4.], [6., 5.], [1., 0.]])
print('Matrix a:')
print(a)
print()

aT = a.transpose()
print('Transpose of matrix a:')
print(aT)

Matrix a:
[[2. 4.]
 [6. 5.]
 [1. 0.]]

Transpose of matrix a:
[[2. 6. 1.]
 [4. 5. 0.]]


In [6]:
# Computing the trace of a matrix

a = np.array([[1., 5., 0.], [2., 4., 10.], [-1., 2., 3.]])
print('Matrix a:')
print(a)
print()

b = a.trace()
print('Trace of matrix a (SUM of main diagonal):')
print(b)

Matrix a:
[[ 1.  5.  0.]
 [ 2.  4. 10.]
 [-1.  2.  3.]]

Trace of matrix a (SUM of main diagonal):
8.0


In [7]:
# Matrix Single Value Decomposition (SVD)

A = np.array([[1, 2], [3, 4], [5, 6]])
print('Matrix A:')
print(A)
print()

# Perform SVD on matrix A
U, S, VT = svd(A)
print('SVD of matrix A:')
print('U:')
print(U)
print('S:')
print(S)
print('VT:')
print(VT)
print()

Matrix A:
[[1 2]
 [3 4]
 [5 6]]

SVD of matrix A:
U:
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
S:
[9.52551809 0.51430058]
VT:
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]



In [8]:
# Compress ratio exercise (PPT Linear Algebra II - Slide 40)
n = 230 # width
d = 219 # height
k = 50 # number of singular values

image_size = n*d # original image size
print('Original image size =', image_size, 'pixels')
print()

image_size_reduced = n*k + k*k + d*k 
print('Reduced image size =', image_size_reduced, 'pixels')
print()

compressRatio = (1 - (image_size_reduced/image_size))*100
print('The compress ratio using', k, 'singular values is =', compressRatio, '%')


Original image size = 50370 pixels

Reduced image size = 24950 pixels

The compress ratio using 50 singular values is = 50.46654754814374 %
